_wandb:
    value:
        cli_version: 0.21.0
        e:
            6p5hkm6apn0a5eghivlwmpoc3zvrr8ay:
                codePath: 14th_trial/reg_main/mixing_training.ipynb
                codePathLocal: mixing_training.ipynb
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1966736678912"
                        used: "345169780736"
                email: gary20000915@gmail.com
                executable: /root/miniconda3/envs/tf/bin/python
                git:
                    commit: c14611c6e1d5e459b4b3edeebde00b2618c5f430
                    remote: git@github.com:yygarypeng/QE-mls.git
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-db30d24c-7dc2-8845-d7b4-6f0f04e79395
                host: bd4e3a269b5c
                memory:
                    total: "134867783680"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /root/work/QE-mls/14th_trial/reg_main/mixing_training.ipynb
                python: CPython 3.11.10
                root: /root/work/QE-mls/14th_trial/reg_main
                startedAt: "2025-07-03T07:35:37.558677Z"
                writerId: 6p5hkm6apn0a5eghivlwmpoc3zvrr8ay
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 7
                - 13
                - 19
                - 38
            "4": 3.11.10
            "5": 0.21.0
            "8":
                - 1
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 512
